config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes do 
    resource :download, only: [:show]
  end 
  get :send_notes_mail, to: 'notes#send_notes_mail', as: :send_notes_mail
  root 'notes#index'

end

app/models/download.rb
require "render_anywhere"

class Download 
  include RenderAnywhere

  def initialize(notes)
    @notes = notes
  end

  def to_pdf 
    # creates the HTML version, then saves 
    kit = PDFKit.new(as_html)
    kit.to_file("tmp/notes.pdf")
  end 

  def filename 
    # for downloads
    "my_notes.pdf"
  end   

  def render_attributes 
    {
      template: "notes/pdf",
      layout: "notes_pdf",
      locals: { notes: notes }
    }
  end 

  private 

  attr_reader :notes 

  def as_html
    # referencing unique layouts
    render render_attributes
  end 
end 

app/models/note.rb
class Note < ActiveRecord::Base
  validates :phone_number, length: { in: 7..13 }
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # helper_method :current_user
  # def current_user
  #   @current_user ||= User.find_by_id(session[:user])
  # end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController

  def show
    respond_to do |format|
      format.pdf { send_note_pdf }
    end 
  end

  private 

  def note 
    Note.where(user: current_user).order("created_at DESC")
  end 

  def download 
    Download.new(note)
  end 

  def send_note_pdf
    send_file download.to_pdf, download_attributes
  end 

  # def send_note_email
  #   NoteMailer.notes_email.deliver_now
  # end 

  def download_attributes
    { 
      filename: download.filename, 
      type: "application/pdf",
      disposition: "attachment"
    }
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.where(user: current_user).order("created_at DESC")
  end

  def send_notes_mail
    NoteMailer.notes_email(current_user).deliver_now
    flash[:notice] = "Email has been sent."
    redirect_to notes_path
  end 

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = current_user.notes.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:name, :phone_number, :date, :time, :body, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_filter :save_login_state, :only => [:log_in]

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to notes_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_filter :save_login_state, :only => [:new, :create]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to notes_path
      flash[:notice] = "You signed up successfully!"
    else
      render "new"
    end
  end

  private 

  def user_params 
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phone Notes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Phone Notes</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "My Notes", notes_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if !current_user.nil? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "danger" : "success" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>  
      <% end %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/layouts/notes_pdf.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
  <meta name="ROBOTS" content ="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <!-- Puts all of the CSS inline, for simplicity -->
  <style>
  	<%= Rails.application.assets.find_asset('note_pdf').to_s %>
  </style>
</head>
	<div class="container">
		<%= yield %>
	</div>


</body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note, html: { multipart: true } do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.text_field :date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :time %><br>
    <%= f.time_select :time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<div class="container">
  <h1>Editing Note</h1>

  <%= render 'form' %>

  <button class="btn"><%= link_to 'Show', @note %></button>
  <button class="btn"><%= link_to 'Back', notes_path %></button>
</div>

app/views/notes/index.html.erb
<div class="container">
  <h1>My Notes</h1>

  <% if @notes.count > 0 %>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="center">Name</th>
        <th class="center">Phone Number</th>
        <th class="center">Date</th>
        <th class="center">Time</th>
        <th class="center">Body</th>
        <th class="center">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @notes.each do |note| %>
        <tr>
          <td><%= note.name %></td>
          <td><%= note.phone_number %></td>
          <td><%= note.date %></td>
          <td><%= note.time.strftime("%H:%M:%S") %></td>
          <td><%= note.body %></td>
          <td> 
            <div class="btn-group">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Actions <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><%= link_to "View", note %></li>
                <li><%= link_to "Edit", edit_note_path(note) %></li>
                <li><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }%></li>
              </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <button class="btn"><%= link_to "Download PDF", note_download_path(@notes, :format => "pdf") %></button>
  <button class="btn"><%= link_to "Send Notes By Email", :controller => "notes", :action => "send_notes_mail" %></button>
  <button class="btn"><%= link_to 'New Note', new_note_path %></button>
  <% else %>

  <h3> No notes to display. Get started by making your first note!</h3>
  <button class="btn"><%= link_to 'New Note', new_note_path %></button>
  <% end %>
  <br>

</div>

app/views/notes/new.html.erb
<div class="container">
  <h1>New Note</h1>

  <%= render 'form' %>

  <button class="btn"><%= link_to 'Back', notes_path %></button>
</div>

app/views/notes/pdf.html.erb
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th class="center">Name</th>
        <th class="center">Phone Number</th>
        <th class="center">Date</th>
        <th class="center">Time</th>
        <th class="center">Body</th>
      </tr>
    </thead>

    <tbody>
      <% notes.each do |note| %>
        <tr>
          <td><%= note.name %></td>
          <td><%= note.phone_number %></td>
          <td><%= note.date %></td>
          <td><%= note.time.strftime("%H:%M:%S") %></td>
          <td><%= note.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/notes/show.html.erb
<div class="container">
  <h3>Name: <%= @note.name %></h3>
    <br>  
  <h5>Phone Number: <%= @note.phone_number %></h5>
    <br>
  <h5>Date: <%= @note.date %></h5>
    <br>
  <h5>Time: <%= @note.time.strftime("%H:%M:%S") %></h5>
    <br>
  <h5>Message: <%= @note.body %></p>
    <br>
</div>